// Generated by e2e/walkthrough.mjs on 2026-09-11T04:39:38.143Z. Do not edit by hand.
import type { Manifest } from './manifest';

export const MANIFEST: Manifest = {
  "title": "Mahgeong",
  "tagline": "The daily geography puzzle, played like mahjong.",
  "outroLine": "197 countries. One board a day. How fast can you clear it?",
  "cta": "Mahgeong · play today’s board",
  "features": [
    {
      "id": "daily",
      "kind": "Daily",
      "title": "One board a day. Same for everyone.",
      "blurb": "No. 1 landed on 11 September. Every player gets the identical deal, so the times are comparable and the bragging is fair.",
      "media": {
        "desktop": {
          "kind": "image",
          "src": "shots/02-daily-desktop.png",
          "w": 1920,
          "h": 1200
        },
        "phone": {
          "kind": "image",
          "src": "shots/02-daily-phone.png",
          "w": 1040,
          "h": 2080
        }
      }
    },
    {
      "id": "match",
      "kind": "How it plays",
      "title": "Pair a country with its capital",
      "blurb": "Tap a country, tap its capital, and the pair lifts off the board. A tile is free when nothing sits on it and one side is open, exactly like mahjong solitaire.",
      "media": {
        "desktop": {
          "kind": "video",
          "src": "clips/desktop.mp4",
          "startSec": 6.966,
          "w": 1280,
          "h": 800
        },
        "phone": {
          "kind": "video",
          "src": "clips/phone.mp4",
          "startSec": 6.688,
          "w": 520,
          "h": 1040
        }
      }
    },
    {
      "id": "hint",
      "kind": "Hints",
      "title": "Stuck? Take a hint. It shows.",
      "blurb": "Hints and shuffles are always there. They ring the pair in gold and leave a gold square in your result, so a clean run means something.",
      "media": {
        "desktop": {
          "kind": "video",
          "src": "clips/desktop.mp4",
          "startSec": 14.077,
          "w": 1280,
          "h": 800
        },
        "phone": {
          "kind": "video",
          "src": "clips/phone.mp4",
          "startSec": 13.714,
          "w": 520,
          "h": 1040
        }
      }
    },
    {
      "id": "flags",
      "kind": "Modes",
      "title": "Flags, currencies, populations too",
      "blurb": "The clue type changes daily. Practice has every mode, four board sizes and a classic random deal for purists.",
      "media": {
        "desktop": {
          "kind": "image",
          "src": "shots/08-flags-desktop.png",
          "w": 1920,
          "h": 1200
        },
        "phone": {
          "kind": "image",
          "src": "shots/08-flags-phone.png",
          "w": 1040,
          "h": 2080
        }
      }
    },
    {
      "id": "share",
      "kind": "Share",
      "title": "Share the grid. Keep the streak.",
      "blurb": "Green for clean pairs, gold for help, red for a wrong guess first. Copy it, post it, and come back tomorrow for No. 2.",
      "media": {
        "desktop": {
          "kind": "image",
          "src": "shots/06-share-desktop.png",
          "w": 1920,
          "h": 1200
        },
        "phone": {
          "kind": "image",
          "src": "shots/06-share-phone.png",
          "w": 1040,
          "h": 2080
        }
      }
    },
    {
      "id": "stats",
      "kind": "Stats",
      "title": "Every day you play, counted",
      "blurb": "Played, streak, best streak, average and fastest times. It lives in your browser, the way the classics did.",
      "media": {
        "desktop": {
          "kind": "image",
          "src": "shots/07-stats-desktop.png",
          "w": 1920,
          "h": 1200
        },
        "phone": {
          "kind": "image",
          "src": "shots/07-stats-phone.png",
          "w": 1040,
          "h": 2080
        }
      }
    }
  ]
};
